### ISSUE TITLE
SIGSEGV occurs if memory allocation fails in ssl3_setup_init_buffer() called by tls13_use_legacy_stack() when downgrading from TLS1.3.

### ISSUE THREAD

**Issue by masanore** [libressl/openbsd#146]
This was found by chance with our Playstation's crash reporting system.
It seems to be occurring since LibreSSL 3.4.0.
The failing part is ssl3_get_message() in ssl3_connect(), which accesses s->init_buf(NULL)->data and crashes.

There seem to be two causes of the problem.

### One is the timing of state changes.

This occurs because ssl3_connect() is called with the SSL3_ST_SR_CLNT_HELLO_A state without init_buffer being prepared.

Before 3.4.0, the process to set s->s3->hs.state to SSL3_ST_SR_CLNT_HELLO_A by tls13_legacy_connect() was after ssl3_setup_init_buffer().
Therefore, if ssl3_setup_init_buffer() failed, the state was not changed.
As a result, ssl3_connect() was called with the SSL_ST_CONNECT state, so ssl3_setup_init_buffer() was called also at ssl3_connect() and did not access NULL.

However, after the commit below, the state became to change when proceeding to legacy_states[mt].recv.
https://github.com/libressl/openbsd/commit/ee251d77c6317226225e35e8c829532dd17d070d
(For reference, commit to delete existing state changes)
https://github.com/libressl/openbsd/commit/8618afba3fa3eb90bdddf39bcd4d984309163e0a

I think it's very good that the state became to progress automatically.
Therefore, for example, a proposed modification would be to delay the timing of changing s->method from tls13_legacy_connect() to ssl3_connect() until preparations for ssl3_connect() are completed, as below.

```
diff --git a/src/lib/libssl/tls13_legacy.c b/src/lib/libssl/tls13_legacy.c
index 1d6a5a129..e30e19c27 100644
--- a/src/lib/libssl/tls13_legacy.c
+++ b/src/lib/libssl/tls13_legacy.c
@@ -322,8 +322,6 @@ tls13_use_legacy_stack(struct tls13_ctx *ctx)

        memset(&cbb, 0, sizeof(cbb));

-       s->method = tls_legacy_method();
-
        if (!ssl3_setup_init_buffer(s))
                goto err;
        if (!ssl3_setup_buffers(s))
@@ -369,6 +367,7 @@ tls13_use_legacy_stack(struct tls13_ctx *ctx)
        s->s3->hs.tls12.reuse_message = 1;
        s->s3->hs.tls12.message_type = tls13_handshake_msg_type(ctx->hs_msg);
        s->s3->hs.tls12.message_size = CBS_len(&cbs) - SSL3_HM_HEADER_LENGTH;
+       s->method = tls_legacy_method();

        return 1;
```

### Another cause is error handling in tls13_handshake_recv_action().

Even if action->recv(ctx, &cbs) fails in tls13_handshake_recv_action() and ret becomes TLS13_IO_FAILURE, TLS13_IO_USE_LEGACY is returned without using the ret when (ctx->ssl->method->version < TLS1_3_VERSION) .
https://github.com/libressl/openbsd/blob/17c60e5b8955deb5786d3f1577b5532478186585/src/lib/libssl/tls13_handshake.c#L548-L566

This causes ssl3_connect()(which was set to s->method) to be called even though tls13_legacy_connect() has failed.

I think this can be fixed by checking the version only when TLS13_IO_SUCCESS, for example as below.

```
diff --git a/src/lib/libssl/tls13_handshake.c b/src/lib/libssl/tls13_handshake.c
index 9723edfea..2b987c405 100644
--- a/src/lib/libssl/tls13_handshake.c
+++ b/src/lib/libssl/tls13_handshake.c
@@ -559,7 +559,7 @@ tls13_handshake_recv_action(struct tls13_ctx *ctx,
        tls13_handshake_msg_free(ctx->hs_msg);
        ctx->hs_msg = NULL;

-       if (ctx->ssl->method->version < TLS1_3_VERSION)
+       if (ret == TLS13_IO_SUCCESS && ctx->ssl->method->version < TLS1_3_VERSION)
                return TLS13_IO_USE_LEGACY;

        return ret;
```

If you fix either one, SIGSEGV will no longer occur, but I think it's better to fix both.

### How to reproduce
The way to reproduce this is to make malloc fail with ssl3_setup_init_buffer(), but this is difficult to test with libressl as is.
I think it would be quick to rewrite and build so that the error always occurs as below.
After that, if you use the command below to connect to a server that only supports TLSv1.2, it will crash.
```
$ ./openssl s_client -connect tls-v1-2.badssl.com:1012

diff --git a/src/lib/libssl/ssl_both.c b/src/lib/libssl/ssl_both.c
index 14d9aa85a..73a8d1bc2 100644
--- a/src/lib/libssl/ssl_both.c
+++ b/src/lib/libssl/ssl_both.c
@@ -463,7 +463,8 @@ ssl3_setup_init_buffer(SSL *s)
        if (s->init_buf != NULL)
                return (1);

-       if ((buf = BUF_MEM_new()) == NULL)
+//     if ((buf = BUF_MEM_new()) == NULL)
+       if (1)
                goto err;
        if (!BUF_MEM_grow(buf, SSL3_RT_MAX_PLAIN_LENGTH))
                goto err;
```
backtrace
```
(defined TLS13_DEBUG, and -6 is TLS13_IO_USE_LEGACY)

$ ./openssl s_client -connect tls-v1-2.badssl.com 1012
WARNING: can't open config file: /usr/local/etc/ssl/openssl.cnf
CONNECTED(00000003)
Client sending ClientHello
Client receiving ServerHello
Client recv returned -6
Segmentation fault (core dumped)
...
Core was generated by `./openssl s_client -connect tls-v1-2.badssl.com 1012'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000052691d in ssl3_get_message (s=s@entry=0x1621f10, st1=st1@entry=4384,
    stn=stn@entry=4385, mt=mt@entry=-1, max=max@entry=20000) at ssl_both.c:361
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-225.el8_8.6.x86_64
(gdb) bt
#0  0x000000000052691d in ssl3_get_message (s=s@entry=0x1621f10, st1=st1@entry=4384,
    stn=stn@entry=4385, mt=mt@entry=-1, max=max@entry=20000) at ssl_both.c:361
#1  0x0000000000529cc1 in ssl3_get_server_hello (s=s@entry=0x1621f10) at ssl_clnt.c:844
#2  0x000000000052b6c8 in ssl3_connect (s=0x1621f10) at ssl_clnt.c:314
#3  0x000000000054c139 in tls13_legacy_write_bytes (ssl=0x1621f10,
    type=<optimized out>, vbuf=<optimized out>, len=0) at tls13_legacy.c:266
#4  0x000000000042603c in s_client_main (argc=<optimized out>, argv=<optimized out>)
    at s_client.c:1379
#5  0x00000000004030d2 in do_cmd (argv=0x7fff49208980, argc=3, prog=0x1618050)
    at openssl.c:510
#6  main (argc=3, argv=0x7fff49208980) at openssl.c:455
```

### LibreSSL version
LibreSSL 3.4.0 - master.

### OS
RockyLinux8

**Comment by botovq** [comment]
Thanks for both reports. We will consider your suggestions and will get
back to you.

For future reference, if fixes are security relevant (these are
borderline) it would be appreciated if you sent mail to
***@***.*** instead of opening an issue here.

**Comment by masanore** [comment]
Hi @botovq,

Thanks,

> For future reference, if fixes are security relevant (these are
> borderline) it would be appreciated if you sent mail to
> ***@***.*** instead of opening an issue here.

OK. If it's security related, I'll email first.
Is the hidden string "libressl-security at openbsd.org"?

**Comment by botovq** [comment]
On Tue, Nov 21, 2023 at 07:25:29AM -0800, Masaru Masuda wrote:
> Hi @botovq,
> 
> Thanks,
> 
> > For future reference, if fixes are security relevant (these are
> > borderline) it would be appreciated if you sent mail to
> > ***@***.*** instead of opening an issue here.
> 
> OK. If it's security related, I'll email first.

Thanks

> Is the hidden string "libressl-security at openbsd.org"?

Yes, sorry about that. I wasn't aware that github did that.

**Comment by bob-beck** [comment]
Just a belated (since I'm reviewing the fix now) thanks for a positively excellent bug report that you gave us everything we needed in.
