### ISSUE TITLE
 SSL_get{_peer,}_signature_type_nid implemented but not exported

### ISSUE THREAD

**Issue by flichtenheld** [libressl/openbsd#147]
The functions `SSL_get_peer_signature_type_nid` and `SSL_get_signature_type_nid` are implemented but not listed in libssl/Symbols.list. Code that uses them compiles (since they are present in header) but fails during link.

**Comment by botovq** [comment]
On Tue, Nov 28, 2023 at 04:31:02AM -0800, Frank Lichtenheld wrote:
> The functions `SSL_get_peer_signature_type_nid` and `SSL_get_signature_type_nid` are implemented but not listed in libssl/Symbols.list. Code that uses them compiles (since they are present in header) but fails during link.

Indeed, this is an oversight. I will definitely fix this for 3.9.x with
the next library bump.

Whether we can/should fix this in the stable branches is unclear to me.
I will need to discuss this with the others as I am unsure if symbol
addition is acceptable. Given that it took 2.5 years for anyone to
notice, it can probably wait.

Thanks for the report!
