### ISSUE TITLE
Compat: Ability to compile without IPv6 support

### ISSUE THREAD

**Issue by projectgoav** [libressl/openbsd#148]
It seems that LibreSSL assumes IPv6 support. When using alternative networking stacks like [LWIP](https://savannah.nongnu.org/projects/lwip/) these can often be configured without IPv6 support which then causes builds to fail. 

The following files are impacted:
`libcrypto\x509\x509_constraints.c`
`libcrypto\bio\bss_dgram.c`
`libssl\ssl_lib.c`
`libtls\tls_internal.h`
`apps\openssl\s_cb.c`
`apps\ocspcheck\http.c`
`apps\ocspcheck\ocspcheck.c`
`apps\nc\socks.c`

libcrypto & libsll can be built by stubbing out a `struct sockaddr_in6` definition but this is just a hack. 

Is there any scope to have IPv6 support configurable?

**Comment by botovq** [comment]
I do not think we want to support this. Out of curiosity: much more than `#define sockaddr_in6 sockaddr` and `#define AF_INET6 AF_INET` is needed for a build with LWIP?

**Comment by projectgoav** [comment]
From what I can gather there is only 2 more defines that are required for an LWIP compatibility shim: `#define INET6_ADDRSTRLEN 46` and an implementation of `inet_pton` that works for ipv6 addresses (LWIP splits these into a v4 & v6 version surrounded by macros). 

Those are easily managed in a compatibility shim so think that would be the better place to manage this.
