### ISSUE TITLE
EVP_get_cipherbynid/EVP_get_digestbynid when given an invalid ID/EVP_get_digestbyname segfaults with NULL argument

### ISSUE THREAD

**Issue by schwabe** [libressl/openbsd#150]
Previous versions were fine when `EVP_get_digestbynid` got a random integer that does not map to any object. In the OpenBSD 7.5 version these function now started to segfault in this case. I think the reason is that the underlying `EVP_get_digestbyname` does not longer accept NULL as argument. 

In OpenVPN we had this admittily a bit hacky code to enumerate all ciphers/digest:

```
    for (int nid = 0; nid < 10000; ++nid)
    {
        const EVP_MD *digest = EVP_get_digestbynid(nid);
        if (digest)
        {
            print_digest(digest, NULL);
        }
    }
```

which now segfaults to due the behaviour change. I have a workaround for the issue in OpenVPN (https://gerrit.openvpn.net/c/openvpn/+/586) that calls `OBJ_nid2sn` to figure out if it is safe to call `EVP_get_digestbyname` but I would like to raise the issue as other software might run into the same issue.

**Comment by botovq** [comment]
On Mon, May 13, 2024 at 03:51:30AM -0700, Arne Schwabe wrote:
> Previous versions were fine when `EVP_get_digestbynid` got a random integer that does not map to any object. In the OpenBSD 7.5 version these function now started to segfault in this case. I think the reason is that the underlying `EVP_get_digestbyname` does not longer accept NULL as argument. 
> 
> In OpenVPN we had this admittily a bit hacky code to enumerate all ciphers/digest:
> 
> ```
>     for (int nid = 0; nid < 10000; ++nid)
>     {
>         const EVP_MD *digest = EVP_get_digestbynid(nid);
>         if (digest)
>         {
>             print_digest(digest, NULL);
>         }
>     }
> ```
> 
> which now segfaults to due the behaviour change. I have a workaround for the issue in OpenVPN (https://gerrit.openvpn.net/c/openvpn/+/586) that calls `OBJ_nid2sn` to figure out if it is safe to call `EVP_get_digestbyname` but I would like to raise the issue as other software might run into the same issue.

Thanks for the report. This issue was fixed shortly after release
precisely because of OpenVPN. It didn't feel important enough for a
backport or errata, as we haven't found other software relying on this:

https://github.com/openbsd/src/commit/ace1aaedae16f4098783ed4a8c5602142650126c

**Comment by cron2** [comment]
Hi,

a backport would be extremely nice :-) - we have upgraded our buildbot infrastructure to a new OpenBSD 7.5 bot, which is not passing selftests now.  Including extra `#ifdef` for this particular version of LibreSSL is not something we're very keen on having in our code...

Out of curiousity, how are the packages built for OpenVPN for OpenBSD?  The ports tree has no patches (relevant for this), but `openvpn --show-ciphers` with the ports-provided binary works juist fine.

gert
  (openvpn upstream maintainer)

**Comment by cron2** [comment]
Thanks for the explanation.  I didn't think of looking at CVS branches :-)
