### ISSUE TITLE
Add SSL_CTX_set1_cert_store

### ISSUE THREAD

**Issue by wahern** [libressl/openbsd#71]
SSL_CTX_set_cert_store does not increment the reference count of the store object. This a trap for the unwary as OpenSSL has been inconsistent in this regard. Some "set_foo" routines will increment the reference, others won't, and my habit has always been to examine the implementations. Newer APIs use the set0_foo and set1_foo, which is a much nicer contract that allows me to relax a little more.

I've been using a fake SSL_CTX_set1_cert_store macro in my projects for a couple of years now which only incremented the reference if SSL_CTX_set_cert_store failed to. (I was afraid somebody might "fix" the routine by incrementing the reference count, causing a leak in my wrapper.) But now that OpenSSL objects are going opaque I can't test the reference count anymore.

OpenSSL is also adding SSL_CTX_set1_cert_store:
  https://github.com/openssl/openssl/pull/1755
  https://github.com/openssl/openssl/issues/1734

**Comment by daurnimator** [comment]
upstream openssl has merged now (in https://github.com/openssl/openssl/commit/b50052dbe822271c9d7b2559a38a127fca87e4ab)

**Comment by daurnimator** [comment]
@busterb was this fixed?

**Comment by busterb** [comment]
oh, pardon, I misread the link
